-- =====================================================
-- Anne's Fashion Line — Supabase PostgreSQL Database Setup
-- Run this script in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/_/sql
-- =====================================================

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'staff',
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    phone VARCHAR(20),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_login TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON public.users(role);

-- 2. CUSTOMERS TABLE
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(100) UNIQUE,
    phone VARCHAR(20),
    address TEXT,
    city VARCHAR(50) DEFAULT 'Nairobi',
    customer_type VARCHAR(20) DEFAULT 'walk-in',
    total_orders INT DEFAULT 0,
    total_spent DECIMAL(10, 2) DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    category VARCHAR(50) NOT NULL,
    sku VARCHAR(50) UNIQUE,
    image_url VARCHAR(500),
    is_active BOOLEAN DEFAULT TRUE,
    is_featured BOOLEAN DEFAULT FALSE,
    allow_preorder BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);
CREATE INDEX IF NOT EXISTS idx_products_sku ON public.products(sku);
CREATE INDEX IF NOT EXISTS idx_products_active ON public.products(is_active);

-- 4. PRODUCT VARIANTS
CREATE TABLE IF NOT EXISTS public.product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    size VARCHAR(10),
    color VARCHAR(50),
    sku VARCHAR(50) UNIQUE,
    is_active BOOLEAN DEFAULT TRUE,
    CONSTRAINT unique_variant UNIQUE (product_id, size, color)
);

-- 5. INVENTORY TABLE
CREATE TABLE IF NOT EXISTS public.inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    variant_id BIGINT REFERENCES public.product_variants(id) ON DELETE CASCADE,
    quantity INT NOT NULL DEFAULT 0,
    reserved_quantity INT NOT NULL DEFAULT 0,
    reorder_point INT DEFAULT 5,
    last_updated TIMESTAMPTZ DEFAULT NOW()
);

-- 6. PRODUCT IMAGES TABLE
CREATE TABLE IF NOT EXISTS public.product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    image_url VARCHAR(500) NOT NULL,
    is_main INT DEFAULT 0
);

-- 7. SALES TABLE
CREATE TABLE IF NOT EXISTS public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_number VARCHAR(20) UNIQUE NOT NULL,
    sale_type VARCHAR(20) NOT NULL,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE SET NULL,
    customer_name VARCHAR(100),
    total_amount DECIMAL(10, 2) NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    payment_status VARCHAR(20) DEFAULT 'paid',
    transaction_reference VARCHAR(100),
    staff_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. SALE ITEMS TABLE
CREATE TABLE IF NOT EXISTS public.sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL REFERENCES public.sales(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
    variant_id BIGINT REFERENCES public.product_variants(id) ON DELETE SET NULL,
    product_title VARCHAR(200) NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(10, 2) NOT NULL,
    total_price DECIMAL(10, 2) NOT NULL
);

-- 9. INVENTORY LOGS TABLE
CREATE TABLE IF NOT EXISTS public.inventory_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    variant_id BIGINT REFERENCES public.product_variants(id) ON DELETE SET NULL,
    quantity_change INT NOT NULL,
    action_type VARCHAR(30) NOT NULL,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    sale_id BIGINT REFERENCES public.sales(id) ON DELETE SET NULL,
    reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.settings (
    setting_key VARCHAR(50) PRIMARY KEY,
    setting_value TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- INSERT DEFAULT SETTINGS
INSERT INTO public.settings (setting_key, setting_value)
VALUES ('pre_order_mode', 'off')
ON CONFLICT (setting_key) DO NOTHING;

-- INSERT DEFAULT ADMIN USER (Password: admin123)
INSERT INTO public.users (username, email, password_hash, role, first_name, last_name)
VALUES (
    'admin',
    'admin@annesfashion.com',
    '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
    'admin',
    'Admin',
    'User'
)
ON CONFLICT (email) DO NOTHING;

-- INSERT DEFAULT STAFF USER (Password: staff123)
INSERT INTO public.users (username, email, password_hash, role, first_name, last_name)
VALUES (
    'staff',
    'staff@annesfashion.com',
    '$2y$10$TKh8H1.PfQx37YgCzwiKb.KjNyWgaHb9cbcoQgdIVFlYg7B77UdFm',
    'staff',
    'Staff',
    'User'
)
ON CONFLICT (email) DO NOTHING;

-- ENABLE ROW LEVEL SECURITY (RLS) FOR PUBLIC READ ACCESS ON PRODUCTS/IMAGES
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Allow public read images" ON public.product_images FOR SELECT USING (true);
CREATE POLICY "Allow public read inventory" ON public.inventory FOR SELECT USING (true);

-- 11. CHAT CONVERSATIONS TABLE
CREATE TABLE IF NOT EXISTS public.chat_conversations (
    id VARCHAR(50) PRIMARY KEY,
    session_id VARCHAR(100) NOT NULL,
    customer_name VARCHAR(100) DEFAULT 'Guest Customer',
    customer_email VARCHAR(100) NULL,
    customer_phone VARCHAR(20) NULL,
    current_product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    current_product_title VARCHAR(250) NULL,
    current_page VARCHAR(250) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'AI_ACTIVE',
    assigned_staff_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    assigned_staff_name VARCHAR(100) NULL,
    last_message TEXT NULL,
    last_message_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_conv_session ON public.chat_conversations(session_id);
CREATE INDEX IF NOT EXISTS idx_chat_conv_status ON public.chat_conversations(status);

-- 12. CHAT MESSAGES TABLE
CREATE TABLE IF NOT EXISTS public.chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(50) NOT NULL REFERENCES public.chat_conversations(id) ON DELETE CASCADE,
    sender_type VARCHAR(20) NOT NULL,
    sender_name VARCHAR(100) NOT NULL,
    sender_id VARCHAR(100) NULL,
    content TEXT NOT NULL,
    metadata TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_msg_conv ON public.chat_messages(conversation_id);

-- ENABLE ROW LEVEL SECURITY FOR CHAT TABLES
ALTER TABLE public.chat_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all select chat_conversations" ON public.chat_conversations FOR SELECT USING (true);
CREATE POLICY "Allow all insert chat_conversations" ON public.chat_conversations FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all update chat_conversations" ON public.chat_conversations FOR UPDATE USING (true);

CREATE POLICY "Allow all select chat_messages" ON public.chat_messages FOR SELECT USING (true);
CREATE POLICY "Allow all insert chat_messages" ON public.chat_messages FOR INSERT WITH CHECK (true);

